# Generated by Django 2.2.6 on 2020-03-24 14:17

import db.utils
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('uuid', models.UUIDField(help_text='UIUD of the recording', primary_key=True, serialize=False)),
                ('date', models.DateTimeField(help_text='Date the conversation took place')),
                ('date_uploaded', models.DateTimeField(auto_now_add=True, help_text='Date the conversation was uploaded')),
                ('duration', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('uuid', models.UUIDField(help_text='UUID of the device (as displayed)', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationSegment',
            fields=[
                ('uuid', models.UUIDField(primary_key=True, serialize=False)),
                ('start_time', models.IntegerField()),
                ('duration', models.IntegerField()),
                ('image', models.ImageField(help_text='Media path of the saved gammatone', unique=True, upload_to=db.utils.path_and_rename)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='db.Conversation')),
            ],
        ),
        migrations.AddField(
            model_name='conversation',
            name='device',
            field=models.ForeignKey(help_text='Device that recorded the conversation', on_delete=django.db.models.deletion.PROTECT, to='db.Device'),
        ),
        migrations.AlterUniqueTogether(
            name='conversation',
            unique_together={('device', 'date')},
        ),
    ]
